"""Add content and duration to LearningResource

Revision ID: f6a24707ad93
Revises: f6940fe05cbd
Create Date: 2025-11-01 03:32:54.901937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a24707ad93'
down_revision = 'f6940fe05cbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.String(length=50), nullable=True))
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_resource', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
        batch_op.drop_column('duration')
        batch_op.drop_column('content')

    # ### end Alembic commands ###
