name: Crowd Sourced Learning - Backend CI/CD

on:
  push:
    branches:
      - main        # only deploy when you push to main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    
      #  Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      #  Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.6'

      #  Install dependencies
      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Trigger Render Deployment
      - name: Deploy to Render
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

     
